#创建service为${PROJECT_NAME}
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAMESPACE}
spec:
  selector:
    app: ${PROJECT_NAME}
    release: canary
  ports:
  - name: http
    targetPort: 8080
    port: 8080

---
#创建后端服务的pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
      release: canary
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
        release: canary
    spec:
      imagePullSecrets:
      - name: aliyun-docker-registry
      containers:
      - name: ${PROJECT_NAME}
        image: ${ALIYUN_CR_REGISTORY}/${ALIYUN_CR_NAMESPACE}/${PROJECT_NAME}:${VERSION}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: |
            -Dspring.data.redis.host=${REDIS_HOST}
            -Dspring.data.redis.password=${REDIS_KEY}

            -Dspring.datasource.dynamic.datasource.mysql.url=jdbc:mysql://${DB_MYSQL_URL}/dev_alinesno_infra_smart_assistant_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
            -Dspring.datasource.dynamic.datasource.mysql.username=${DB_MYSQL_USRENAME}
            -Dspring.datasource.dynamic.datasource.mysql.password=${DB_MYSQL_PASSWORD}

            -Dspring.datasource.dynamic.datasource.postgresql.url=jdbc:postgresql://${DB_PGVECTOR_URL}/dev_alinesno_infra_base_search_vector_v110
            -Dspring.datasource.dynamic.datasource.postgresql.username=${DB_PGVECTOR_USERNAME}
            -Dspring.datasource.dynamic.datasource.postgresql.password=${DB_PGVECTOR_PASSWORD}

            -Dalinesno.infra.smart.brain.qianwen.key=${QIANWEN_SK}
            
            -Dalinesno.infra.qiniu.access-key=${QINIU_ACCESS_KEY}
            -Dalinesno.infra.qiniu.secret-key=${QINIU_SECRET_KEY}
            -Dalinesno.infra.qiniu.bucket=${QINIU_BUCKET_NAME}
            -Dalinesno.infra.qiniu.domain=${QINIU_BUCKET_DOMAIN}
            
            -Dalinesno.infra.qiniu.bucket-pub=${QINIU_BUCKET_NAME_PUB}
            -Dalinesno.infra.qiniu.domain-pub=${QINIU_BUCKET_DOMAIN_PUB}
            
            -Dserver.port=8080
        ports:
        - name: http
          containerPort: 8080

#            -Dalinesno.infra.gateway.host=${INFRA_GAGTEWAY}

---
#创建域名服务
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${PROJECT_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "${PROJECT_NAME}.${INFRA_DEV_DOMAIN}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ${PROJECT_NAME}
            port:
              number: 8080