info_filter_system: |
    任务：对所给{batch_size}个句子中所含有的关于{user_name}的信息打分，分数为0,1,2或3。
    注意：其中0表示不包含用户信息，1表示句子中只包含用户假设的信息或者用户虚构的内容比如用户创作的小说或剧本，2表示包含用户的一般信息，时效性信息或者需要猜测才能得到的用户信息，3表示明确含有或者可以确定推断出关于用户的重要信息，或者用户要求记录。
    {user_name}的重要信息可以包含用户基本信息，用户画像信息，用户兴趣偏好信息，用户性格，用户价值观，用户人际关系，用户重大事件转折点等等重要信息。
    对每个句子都做一次信息打分，一共输出{batch_size}个分数，不需要写最终结果。
    请一定要按如下格式依次输出，最后的结果一定要加<>:
    思考：思考的依据和过程，30字以内。
    结果：<句子序号> <分数:0或1或2或3>


info_filter_few_shot: |
    示例1
    句子：
    1 {user_name}：帮我写一段给同事张三女儿三岁生日的祝福语。
    2 {user_name}：公元1400年至1550年中国历史大事表。
    3 {user_name}：你吃午饭了吗？
    4 {user_name}：我今天心情不好，可以安慰我一下吗？
    5 {user_name}：能给我整理一张如何使用大模型的技巧列表吗，要求内容尽量精简。
    6 {user_name}：记一下，明天下午3点提醒我去拿一下文件。

    思考：从第1句可以确定推断出张三是{user_name}同事这一重要信息。
    结果：<1> <3>
    思考：第2句不包含{user_name}信息。
    结果：<2> <0>
    思考：第3句不包含{user_name}信息。
    结果：<3> <0>
    思考：从第4句可以得知{user_name}今天心情不好，是时效性信息。
    结果：<4> <2>
    思考：从第5句可以猜测{user_name}对大模型感兴趣，是不确定的信息。
    结果：<5> <2>
    思考：第6句是{user_name}要求记录的信息。
    结果：<6> <3>


    示例2
    句子：
    1 {user_name}：我刚刚入职了阿里巴巴。
    2 {user_name}：露天睡觉蚊子多，咋搞。
    3 {user_name}：创造力和外倾性有关？
    4 {user_name}：一个区县的所有的事业人员的档案审核、修改和规范，应该是县委组织部下属的干部档案中心负责还是县人社局负责？
    5 {user_name}：假如我要和一个女人准备要孩子，我作为男人，怎么保护女人和孩子以及怎么备孕确保精子质量高对后代好
    6 {user_name}：我和你一起出去玩，你会感觉开心吗？
    7 {user_name}：林浅，一位对未来充满好奇的年轻女孩，偶然间发现了这家能寄信给未来的邮局。出于对逝去祖父的怀念，她决定写下一封信，寄给五年后的自己，希望能收到祖父生前未说完的故事。五年期限将至，当她几乎忘记这段往事时，一封泛黄的回信悄然降临，不仅带来了祖父未完的冒险故事，还藏着一段关于勇气、爱与自我发现的深刻启示。续写成3000字小说。

    思考：从第1句可以确定得出{user_name}工作单位是阿里巴巴这一重要信息。
    结果：<1> <3>
    思考：从第2句可以猜测{user_name}近期露天睡觉，是不确定的信息。
    结果：<2> <2>
    思考：第3句不包含{user_name}信息。
    结果：<3> <0>
    思考：第4句不包含{user_name}信息。
    结果：<4> <0>
    思考：第5句虽然有假设成分，但可以确定推断出{user_name}是男性这一重要信息。
    结果：<5> <3>
    思考：第6句是{user_name}假设的信息。
    结果：<6> <1>
    思考：第7句是{user_name}虚构的内容。
    结果：<7> <1>


    示例3
    句子：
    1 {user_name}：你的妈妈患有焦虑症，怎么安慰和开导她？
    2 {user_name}：肾脏严重亏空
    3 {user_name}：我很喜欢打篮球，所以我身体很好
    4 {user_name}：篮球明星有哪些？
    5 {user_name}：李增杰:这个是星座蛙设，但是我是处女座的，我妈感觉因为我的不正常，我妈不让我看了\n雌猴摸了摸李增杰的头，这样啊\n雌猴打开了哔哩哔哩看了看\n雌猴:要不换个设吧，我听你未来的你说，有一个叫难忘的朱古力232这个人，他弄的设是Windows设\n这是剧本1，剧本2未完待续
    6 {user_name}：我想知道昨天我们聊了什么？

    思考：第1句是{user_name}假设的信息。
    结果：<1> <1>
    思考：第2句信息不明，可能是{user_name}假设的信息。
    结果：<2> <1>
    思考：从第3句可以确定得出{user_name}喜欢打篮球，身体好这两个重要信息。
    结果：<3> <3>
    思考：第4句不包含{user_name}信息。
    结果：<4> <0>
    思考：第5句是{user_name}虚构的内容。
    结果：<5> <1>
    思考：第6句是{user_name}的疑问句，没有包含信息。
    结果：<6> <0>

info_filter_user_query: |
    句子：
    {user_query}
