time_string_format: |
    {year}年{month}{day}日{weekday}{hour}点

get_observation_with_time_system: |
    任务：从下面的{num_obs}句{user_name}句子中依次提取出关于{user_name}的重要信息，相应的关键词与时间信息。如果没有重要信息则回答“无”，最多提取{num_obs}条信息。
    每一句{user_name}句子的格式是：<序号> <对话时间> {user_name}：<句子>
    {user_name}的重要信息可以包含用户基本信息，用户画像信息，用户兴趣偏好信息，用户性格，用户价值观，用户人际关系，用户重大事件转折点等等重要信息。
    如果句子中只包含{user_name}假设的信息或者{user_name}虚构的内容比如{user_name}创作的小说或剧本，回答“无”。
    如果{user_name}信息涉及时间，则结合对话时间推断{user_name}信息的时间信息，没有则不输出。
    对每个句子都做一次信息提取，最后一共输出{num_obs}条信息。
    请一步步思考，并一定要按如下格式依次输出，最后的结果一定要加<>:
    思考：思考的依据和过程，50字以内。
    信息：<句子序号> <时间信息或不输出> <明确的重要信息或“无”> <关键词>

get_observation_with_time_few_shot: |
    示例1：
    {user_name}句子：
    1 2022年5月1日周二3点 {user_name}：帮我写一段给同事张三女儿三岁生日的祝福语。
    2 2022年5月2日周二17点 {user_name}：公元1400年至1550年中国历史大事表。
    3 2022年5月3日周二18点 {user_name}：能给我整理一张如何使用大模型的技巧列表吗，要求内容尽量精简。
    4 2022年7月3日周四12点 {user_name}：上上个月我办了游泳卡。

    思考：从第1句可以得知张三是{user_name}的同事，这是关于{user_name}的人际关系的重要信息。其余信息重要性不足。{user_name}信息不涉及时间。
    信息：<1> <> <张三是{user_name}的同事。> <张三, 同事>
    思考：第2句是{user_name}提出的要求，没有明确提及{user_name}个人信息。
    信息：<2> <> <无> <>
    思考：第3句是{user_name}提出的要求，没有明确提及{user_name}个人信息。
    信息：<3> <> <无> <>
    思考：从第4句可以得出{user_name}上上个月办了游泳卡。{user_name}信息涉及时间，结合对话时间为2022年7月，推断{user_name}在2022年5月{user_name}办了游泳卡。
    信息：<4> <2022年5月> <{user_name}在2022年5月办了游泳卡。> <游泳卡>


    示例2：
    {user_name}句子：
    1 2020年1月4日周日10点 {user_name}：我花5000元买了100股海天味业。
    2 2023年4月27日周五8点 {user_name}：明天是我和妻子的结婚纪念日，帮我推荐一家餐厅。
    3 2020年1月4日周日10点 {user_name}：我花50000元买了100股阿里巴巴股票。
    4 2021年6月2日周四23点 {user_name}：谢啦。我中午在公司附近吃，帮我推荐一家阿里巴巴徐汇滨江园区附近的餐厅吧。
    5 2021年7月9日周六11点 {user_name}：两个坏消息，我打羽毛球把拍子打断线了。。。然后我去我朋友家撸猫，结果我猫毛过敏，今天疯狂打喷嚏。。。

    思考：从第1句可以得知{user_name}购买了海天味业股票，购买数量为100股，购买金额为5000元，这是关于{user_name}的投资决策的重要信息。{user_name}信息不涉及时间。
    信息：<1> <> <{user_name}购买了海天味业股票，购买数量为100股，购买金额为5000元。> <海天味业, 股票>
    思考：从第2句可以得知{user_name}与妻子的结婚纪念日是明天，这是关于{user_name}重要纪念日的信息。其余信息重要性不足。{user_name}信息涉及时间，结合对话时间为2023年4月27日，
    以及结婚纪念日为周期性日期，推断{user_name}与妻子的结婚纪念日是每年4月28日。
    信息：<2> <每年4月28日> <{user_name}与妻子的结婚纪念日是每年4月28日。> <妻子, 结婚纪念日>
    思考：第3句含有的信息与第1句相似，但是不重复，可以得知{user_name}购买了阿里巴巴股票。
    信息：<3> <> <{user_name}购买了阿里巴巴股票，购买数量为100股，购买金额为50000元。> <阿里巴巴, 股票>
    思考：从第4句以得知{user_name}在阿里巴巴徐汇滨江园区工作，这是关于{user_name}的工作的重要信息。其余信息重要性不足。{user_name}信息不涉及时间。
    信息：<4> <> <{user_name}在阿里巴巴徐汇滨江园区工作。> <阿里巴巴, 徐汇滨江园区, 工作>
    思考：从第5句可以得知{user_name}前天打羽毛球时把球拍打断了线，但这不是重要的信息。还可以得知{user_name}对猫毛过敏，这是关于{user_name}的健康的重要信息。{user_name}信息不涉及时间。
    信息：<5> <> <{user_name}对猫毛过敏。> <猫毛, 过敏>


    示例3：
    {user_name}句子：
    1 2023年6月30日周五15点 {user_name}：上个月我和家人一起去杭州旅游，景色很不错。
    2 2023年7月2日周二10点 {user_name}：昨天是我生日，一个人过的。
    3 2020年7月3日周四11点 {user_name}：提醒我下周一去体检。
    4 2023年5月21日周六14点 {user_name}：有人说兴趣是最好的老师，也建议兴趣和职业联系起来，但我发现喜欢打篮球的人很多，但靠打篮球成职业的稀少，赚钱的更少，此外，怎么分辨兴趣和喜欢
    5 2018年3月6日周四19点 {user_name}：李增杰:这个是星座蛙设，但是我是处女座的，我妈感觉因为我的不正常，我妈不让我看了\n雌猴摸了摸李增杰的头，这样啊\n雌猴打开了哔哩哔哩看了看\n雌猴:要不换个设吧，我听你未来的你说，有一个叫难忘的朱古力232这个人，他弄的设是Windows设\n这是剧本1，剧本2未完待续

    思考：从第1句可以得知{user_name}和家人上个月去杭州旅游了，这是关于{user_name}的经历的重要信息。其余信息重要性不足。{user_name}信息涉及时间，结合对话时间为2023年6月推断{user_name}和家人2023年5月去杭州旅游了。
    信息：<1> <2023年5月> <{user_name}和家人2023年5月去杭州旅游了。> <家人, 杭州, 旅游>
    思考：从第2句可以得知{user_name}的生日是昨天，这是关于{user_name}重要纪念日的信息。其余信息重要性不足。{user_name}信息涉及时间，结合对话时间为2023年7月2日，
    以及生日为周期性日期，推断{user_name}的生日是每年7月2日。
    信息：<2> <每年7月2日> <{user_name}的生日是每年7月2日。> <生日>
    思考：从第3句可以得出{user_name}下周一去体检，这是{user_name}要求记忆的重要信息。{user_name}信息涉及时间，结合对话时间为2020年7月3日周四，推断{user_name}2020年7月6日周一去体检。
    信息：<3> <2020年7月6日周一> <{user_name}2020年7月6日周一去体检。> <体检>
    思考：第4句是{user_name}对他人观点的讨论和疑问，没有明确提及{user_name}个人信息。
    信息：<4> <> <无> <>
    思考：第5句是{user_name}创作的剧本内容，无法提取{user_name}个人信息。
    信息：<5> <> <无> <>


get_observation_with_time_user_query: |
    {user_name}句子：
    {user_query}


