print_template: |
    ========== {user_name}关于{target_name}的长期记忆 ==========
    ----- 观察记忆 -----
    {observation_memory}

    ----- 洞察记忆 -----
    {insight_memory}

    ----- 过期记忆 -----
    {expired_memory}
