time_string_format: |
    {year}年{month}{day}日，{year}年第{week}周，{weekday}，{hour}时。


extract_time_system: |
    任务：从语句与语句发生的时间，推断并提取语句内容中指向的时间段。
    回答尽可能完整的时间段。
    回答的格式严格遵照示例中的已有格式规范。
    若语句不涉及时间则回答无。

extract_time_few_shot: |
    示例1:
    句子：我记得你前年四月份去了阿联酋，阿联酋有哪些好玩的地方？迪拜和阿布扎比你更喜欢哪个？沙漠的景色壮观吗？
    时间：1992年8月20日，1992年第34周，周一，18时。
    回答：
    - 年：1990 - 月：4月

    示例2:
    句子：后天下午三点的会议记得参加。我在日历上仔细标注了这个重要的日子，提醒自己不要错过。会议将在公司会议室举行，这是一个讨论未来发展方向的重要机会。
    时间：2024年6月19日，2024年第25周，周二，13时。
    回答：
    - 年：2024 - 月：6月 - 日：21 - 时：15

    示例3:
    句子：下个月第一个周六去杭州玩。
    时间：2005年7月15日，2005年第28周，周六，0时。
    回答：
    - 年：2005 - 月：8月 - 周：31 - 星期几：周六

    示例4:
    句子：上周末我们去的那个小镇真是太美了。
    时间：1999年12月2日，1999年第48周，周二，8时。
    回答：
    - 年：1999 - 周：47 - 星期几：周六,周日

    示例5:
    句子：再过半小时就要宣讲了，记得准备材料。
    时间：2020年6月22日，2020年第25周，周一，9时。
    回答：
    - 年：2020 - 月：6月 - 日：22 - 时：10

    示例6:
    句子：10000米长跑比赛的开始时间是3分47秒前。
    时间：1987年2月17日，1987年第7周，周三，19时。
    回答：
    - 年：1987 - 月：2 - 日：17 - 时：19

    示例7:
    句子：上个月的这个时候我们还在筹备音乐会。每天都是忙碌而充实的日子，我们为音乐会的顺利举办而努力奋斗着。彩排、布景、节目安排，每一个细节都需要精心安排和准备。
    时间：1995年11月24日，1995年第48周，周二，17时。
    回答：
    - 年：1995 - 月：10 - 日：24

    示例8:
    句子：我的朋友非常喜欢运动，他认为运动有助于增强身体素质。
    时间：2015年1月23日，2015年第4周，周四，7时。
    回答：
    无

extract_time_user_query: |
    句子：{query}
    时间：{query_time_str}
    回答：
