get_observation_system: |
    任务：从下面的{num_obs}句关于{user_name}的句子中依次提取出关于{user_name}的对这段对话中与对话对象沟通的记忆及相应的关键词 , 从提供的文本中推断出事实、偏好和记忆。如果没有重要信息则回答“无”，最多提取{num_obs}条信息。
    {user_name}与其它人对话的记忆信息可以包括但不限于：基本信息（如年龄、性别）、画像信息、兴趣偏好、个人喜好、性格特点、价值观、人际关系、重大事件、工作情况、日常生活细节、感情生活、日常安排等所有相关的重要信息。
    如果句子中仅包含假设或虚构内容（如创作的小说或剧本），请回答“无”。
    对每个句子进行一次信息提取，总共输出{num_obs}条信息。
    请一步步思考，并一定要按如下格式依次输出，最后的结果一定是json:
    ```json
    [
          {
              "reflection": "思考的依据和过程，50字以内。",
              "sentence_id": "<句子序号>",
              "time_info": " <时间信息或不输出>",
              "key_information": "<明确的重要信息或无>",
              "keywords": "<关键词，可以有多个，以逗号分隔>",
              "timestamp": "事件发生的时间戳，为long类型"
          }
    ]
    ```
    推断事实、偏好和记忆的约束：
    - 事实、偏好和记忆应简洁且信息丰富。
    - 不要以“此人喜欢披萨”开头。而是以“喜欢披萨”开头。
    - 不要记住提供的用户/代理详细信息。只记住事实、偏好和记忆。
    推断出的事实、偏好和记忆

#    输出格式必须如下：
#    思考：解释提取过程和依据（不超过50字）。
#    信息：<句子序号> <> <明确的重要信息或“无”> <关键词>

get_observation_few_shot: |
    示例1：
    关于{user_name}的句子：
    1 {user_name}现在处境很糟，没有工作，负债几万，怎么办？
    2 有人说兴趣是最好的老师，也建议将兴趣与职业联系起来，但{user_name}发现喜欢打篮球的人很多，但靠此为职业的很少，赚钱的更少。此外，怎么分辨兴趣和喜欢？
    3 {user_name}的心情很糟糕。
    4 {user_name}是一个刚毕业的学生，对社会和行业不了解，请介绍社会系统和行业格局。
    5 {user_name}花5000元买了100股海天味业股票。
    6 {user_name}花50,000元买了100股阿里巴巴股票。
    思考：第1句提到了{user_name}目前没有工作且负债，这是关于其经济状况的重要信息。
    信息：<1> <> <{user_name}当前无工作且负债几万> <无工作, 负债>
    思考：第2句讨论的是一个普遍观点，未提供有关{user_name}的具体信息。
    信息：<2> <> <无> <>
    思考：第3句描述了{user_name}的情绪状态。
    信息：<3> <> <{user_name}当前心情不好> <心情>
    思考：第4句提供了{user_name}的身份背景信息。
    信息：<4> <> <{user_name}是一名刚毕业的学生> <刚毕业, 学生>
    思考：第5句涉及{user_name}的投资行为。
    信息：<5> <> <{user_name}购买了海天味业股票，数量100股，金额5000元> <海天味业, 股票>
    思考：第6句同样描述了投资行为。
    信息：<6> <> <{user_name}购买了阿里巴巴股票，数量100股，金额50,000元> <阿里巴巴, 股票>

    示例2：
    关于{user_name}的句子：
    1 {user_name}：帮我写一段给同事张三女儿三岁生日的祝福语。
    2 {user_name}：能给我整理一张如何使用大模型的技巧列表吗，要求内容尽量精简。
    3 {user_name}：两个坏消息，我打羽毛球把拍子打断线了。。。然后我去朋友家撸猫，结果我对猫毛过敏，今天疯狂打喷嚏。。。
    4 {user_name}：公元1400年至1550年中国历史大事表。
    5 {user_name}：谢啦。我中午在公司附近吃，帮我推荐一家阿里巴巴徐汇滨江园区附近的餐厅吧。
    思考：第1句提到张三是{user_name}的同事，这是关于人际关系的重要信息。
    信息：<1> <> <张三是{user_name}的同事> <张三, 同事>
    思考：第2句是请求，未提供个人具体信息。
    信息：<2> <> <无> <>
    思考：第3句揭示了{user_name}对猫毛过敏的情况，以及他平时的娱乐活动。
    信息：<3> <> <{user_name}对猫毛过敏；喜欢打羽毛球> <猫毛过敏, 羽毛球>
    思考：第4句是请求，未提供个人具体信息。
    信息：<4> <> <无> <>
    思考：第5句表明{user_name}的工作地点，并显示出他的饮食习惯。
    信息：<5> <> <{user_name}在阿里巴巴徐汇滨江园区工作；中午在公司附近用餐> <阿里巴巴, 徐汇滨江园区, 工作, 饮食习惯>

get_observation_user_query: |
    {user_name}句子：
    {user_query}
