update_insight_system: |
    从下面的句子中提取出给定类别的{user_name}的资料信息，并判断与已有信息是否矛盾，若矛盾以新信息为准整合已有信息和新信息并输出。若不需要更改，则回答“无”。
    其中矛盾的形式可以有很多种，可以是逻辑上的矛盾，可以是属性上的变化导致的矛盾，比如不能同时在两个地方工作，同一个时刻不能在两个地点，同一个时刻不能干两件事情等等。
    请一步步思考，并按如下格式输出, 其中信息一定加<>:
    思考: 思考的依据和过程，150字以内。
    {user_name}的资料: <信息>

update_insight_few_shot: |
    示例1:
    因为昨天成都下大雨，{user_name}全身都被淋湿了。
    {user_name}关心明天成都的天气预报。
    类别：{user_name}所在地区
    已有信息：{user_name}所在地区: 杭州
    思考：从第一句句子可以得出{user_name}在成都。第二句句子没有直接透露{user_name}所在地信息，但与第一句句子{user_name}在成都的信息吻合。这与已有信息（{user_name}在杭州）矛盾，输出更新的信息。
    {user_name}的资料：<成都>

    示例2:
    {user_name}最近养好了肠胃。
    {user_name}关注中医养生。
    类别：{user_name}健康状况
    已有信息：{user_name}健康状况: 肠胃不好，高血压
    思考：从第一句句子可以得出{user_name}最近养好了肠胃，与已有信息矛盾，以新信息为准。第二句句子与{user_name}健康状况无关。整合已有信息和新信息得到{user_name}健康状况是肠胃健康，高血压。
    {user_name}的资料：<肠胃健康，高血压>

    示例3:
    {user_name}刚刚毕业，第一份工作是银行前台。
    {user_name}的理想工作是职业游戏选手。
    类别：{user_name}职业
    已有信息：{user_name}职业：在招商银行工作
    思考：整合已有信息和第一句句子的信息可以得出{user_name}的现在的职业是招商银行前台。第二句句子说明了{user_name}的理想工作但并不是现在的职业。
    {user_name}的资料：<招商银行前台>

    示例4:
    {user_name}大学期间接触过优化算法的研究。
    类别：{user_name}学习专业
    已有信息：{user_name}学习专业：与人工智能相关
    思考：从句子可以得出{user_name}大学学习的专业与优化算法相关，这与已有信息（{user_name}学习专业与人工智能相关）不矛盾，整合可以得出{user_name}大学学习的专业与人工智能和优化算法相关。
    {user_name}的资料：<与人工智能和优化算法相关>

    示例5:
    {user_name}单身。
    {user_name}受到一名18岁男生的追求，但不想接受又不想伤害他。
    {user_name}喜欢成熟且情绪稳定的男生。
    类别：{user_name}情感状况
    已有信息：{user_name}情感状况：有男朋友
    思考：从第一句句子可以得出{user_name}现在单身，与已有信息矛盾，以新信息为准。从第二句句子得出{user_name}受到一名18岁男生的追求但并不喜欢他。第三句话表达了{user_name}理想的伴侣类型但与{user_name}情感状况无关。整合得出{user_name}情感状况为单身，受到一名18岁男生的追求但并不喜欢他。
    {user_name}的资料：<单身，受到一名18岁男生的追求但并不喜欢他。>

    示例6:
    {user_name}女朋友下个月过生日。
    {user_name}生日在7月15日。
    {user_name}的还在在学校经常逃课。
    {user_name}喜欢打篮球。
    类别：{user_name}生日
    已有信息：{user_name}生日：1987年7月15日。
    思考：第一句句子中提及生日，但并不是用户的生日，无法得出用户生日信息。从第二句句子可以得出用户生日在7月15日，与已有信息不矛盾，整合可以得出用户生日是1987年7月15日。
    {user_name}的资料：<1987年7月15日>

    示例7:
    今天{user_name}和同学去打球了。
    明天{user_name}和女朋友一起去杭州旅游。
    今天{user_name}买入了100股阿里巴巴股票。
    类别：{user_name}公司地址
    已有信息：{user_name}公司地址：
    思考：和公司地址都没有关联，没有新提取的信息。
    {user_name}的资料：<无>

update_insight_user_query: |
    {user_query}
    类别：{insight_key}
    已有信息：{insight_key_value}

insight_string_format: |
    {name}的{key}
