CREATE TABLE `generate_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '唯一ID号',
  `business_id` VARCHAR(255) NOT NULL COMMENT '业务ID',
  `prompt_id` VARCHAR(255) NOT NULL COMMENT 'GPT角色ID',
  `system_content` TEXT COMMENT 'GPT角色设定',
  `user_content` TEXT COMMENT 'GPT用户信息',
  `task_status` INT NOT NULL COMMENT '0排队中/1运行中/2已完成/9失败',
  `has_delete` INT DEFAULT 0 COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` BIGINT COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  `assistant_content` VARCHAR(255) COMMENT '生成内容',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `prompt_posts` (
    `id` BIGINT NOT NULL COMMENT '唯一ID号',
    `use_count` BIGINT COMMENT '指令使用次数',
    `prompt_author` VARCHAR(255) COMMENT '指令管理员',
    `prompt_content` TEXT COMMENT '指令内容',
    `prompt_name` VARCHAR(255) COMMENT '指令名称',
    `prompt_password` VARCHAR(255) COMMENT '指令密钥',
    `prompt_status` BIGINT COMMENT '指令状态',
    `prompt_title` VARCHAR(255) COMMENT '指令标题',
    `prompt_type` VARCHAR(255) COMMENT '指令类型',
    `to_ping` VARCHAR(255) COMMENT '对外',
    `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
    `delete_manager` BIGINT COMMENT '删除的人',
    `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
    `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
    `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
    `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
    `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
    `field_prop` VARCHAR(255) COMMENT '字段属性',
    `add_time` DATETIME COMMENT '添加时间',
    `delete_time` DATETIME COMMENT '删除时间',
    `has_status` INT COMMENT '状态(0启用|1禁用)',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
    `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Prompt指令集实体类';

CREATE TABLE `user_prompt_collection` (
  `id` BIGINT NOT NULL COMMENT '唯一ID号',
  `user_id` BIGINT COMMENT '用户标识',
  `collected_prompt` VARCHAR(255) COMMENT '收集资源',
  `sorting_order` BIGINT COMMENT '排序',
  `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` BIGINT COMMENT '删除的人',
  `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
  `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` VARCHAR(255) COMMENT '字段属性',
  `add_time` DATETIME COMMENT '添加时间',
  `delete_time` DATETIME COMMENT '删除时间',
  `has_status` INT COMMENT '状态(0启用|1禁用)',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户指令收藏';

CREATE TABLE `prompt_catalog` (
  `id` bigint NOT NULL COMMENT '唯一ID号',
  `industry_category` varchar(255) DEFAULT NULL COMMENT '行业分类',
  `business_category` varchar(255) DEFAULT NULL COMMENT '业务分类',
  `management_object` varchar(255) DEFAULT NULL COMMENT '管理对象',
  `information_type` varchar(255) DEFAULT NULL COMMENT '信息类别',
  `subject_category` varchar(255) DEFAULT NULL COMMENT '主题分类',
  `resource_provider` varchar(255) DEFAULT NULL COMMENT '资源提供方',
  `source_system` varchar(255) DEFAULT NULL COMMENT '来源系统',
  `source_data_table` varchar(255) DEFAULT NULL COMMENT '来源数据表',
  `status` varchar(255) DEFAULT NULL COMMENT '状态',
  `has_delete` int DEFAULT NULL COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` bigint DEFAULT NULL COMMENT '删除的人',
  `application_id` bigint DEFAULT NULL COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` varchar(64) DEFAULT NULL COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` bigint DEFAULT NULL COMMENT '所属租户 , 租户权限',
  `field_id` varchar(255) DEFAULT NULL COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` bigint DEFAULT NULL COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` varchar(255) DEFAULT NULL COMMENT '字段属性',
  `add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `has_status` int DEFAULT NULL COMMENT '状态(0启用|1禁用)',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` bigint DEFAULT NULL COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` bigint DEFAULT NULL COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Prompt指令类型实体类';


CREATE TABLE `prompt_model` (
  `id` bigint NOT NULL COMMENT '唯一ID号',
  `model_name` varchar(255) DEFAULT NULL COMMENT '模型名称',
  `industry_category` varchar(255) DEFAULT NULL COMMENT '行业分类',
  `business_category` varchar(255) DEFAULT NULL COMMENT '业务分类',
  `resource_name` varchar(255) DEFAULT NULL COMMENT '资源名称',
  `resource_summary` varchar(255) DEFAULT NULL COMMENT '资源摘要',
  `model_description` varchar(255) DEFAULT NULL COMMENT '模型描述',
  `model_fields` varchar(255) DEFAULT NULL COMMENT '模型字段',
  `model_source` varchar(255) DEFAULT NULL COMMENT '模型来源',
  `model_tags` varchar(255) DEFAULT NULL COMMENT '模型标签',
  `has_delete` int DEFAULT NULL COMMENT '是否删除(1删除|0正常|null正常)',
  `delete_manager` bigint DEFAULT NULL COMMENT '删除的人',
  `application_id` bigint DEFAULT NULL COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
  `application_name` varchar(64) DEFAULT NULL COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
  `tenant_id` bigint DEFAULT NULL COMMENT '所属租户 , 租户权限',
  `field_id` varchar(255) DEFAULT NULL COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
  `department_id` bigint DEFAULT NULL COMMENT '部门权限: 只能看到自己所在部门的数据',
  `field_prop` varchar(255) DEFAULT NULL COMMENT '字段属性',
  `add_time` datetime DEFAULT NULL COMMENT '添加时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  `has_status` int DEFAULT NULL COMMENT '状态(0启用|1禁用)',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `operator_id` bigint DEFAULT NULL COMMENT '操作员 用户权限: 只能看到自己操作的数据',
  `last_update_operator_id` bigint DEFAULT NULL COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='模型管理实体类';
