# Deployment 配置
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.kuboard.cn/name: ubuntu
  name: ubuntu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.kuboard.cn/name: ubuntu
  template:
    metadata:
      labels:
        k8s.kuboard.cn/name: ubuntu
    spec:
      containers:
        - image: dorowu/ubuntu-desktop-lxde-vnc:latest
          name: ubuntu-desktop-lxde-vnc

---
# Service 配置
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s.kuboard.cn/name: ubuntu
  name: ubuntu
  namespace: default
spec:
  ports:
    - name: rfjwrr
      nodePort: 26180
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 33nyzm
      nodePort: 25911
      port: 5901
      protocol: TCP
      targetPort: 5901
  selector:
    k8s.kuboard.cn/name: ubuntu
  type: NodePort

---
# Ingress 配置
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${PROJECT_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "${PROJECT_NAME}.${INFRA_DEV_DOMAIN}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ubuntu
                port:
                  number: 25911